<?php

/**
 * @file
 * Contains the main module file for the Simple Voting module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function simple_vote_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.simple_vote':
      drupal_set_message(t('This module provides a simple voting system.'));
      break;
  }
}

/**
 * Implements hook_menu().
 */
function simple_vote_menu() {
  $items = [];

  $items['voting'] = [
    'title' => 'Voting',
    'page callback' => 'simple_vote_display',
    'access callback' => TRUE,
  ];

  return $items;
}